### ISSUE TITLE
plotranking() does not scale plots appropriately 

### ISSUE THREAD

**Issue by danielwilhelm** [danielwilhelm/R-CS-ranks#1]
Problem: the function plotranking() produces plots that look nice in the PISA example, but then don't scale properly when fewer or more objects are to be ranked (see, e.g., the example in https://danielwilhelm.github.io/R-CS-ranks/reference/plotranking.html)

**Comment by MrDomani** [comment]
IMHO fixed. Now the width of errorbar does not depend on the amount of categories. Changes reside on dev branch, will be merged to master soon.
