### ISSUE TITLE
sd -> V

### ISSUE THREAD

**Issue by MrDomani** [danielwilhelm/R-CS-ranks#12]
Instead of vector of standard distributions, we will expect a (possibly diagonal) covariance matrix.

**Comment by MrDomani** [comment]
During our meeting, we came up with name `V` for the covariance matrix argument. However, in my experience the canonical way to denote a covariance matrix is with Sigma letter. Function, that generates observations from multivariate normal distribution, calls the covariance matrix argument `Sigma`. Maybe we should do the same? How is the covariance matrix usually denoted in economic/econometric literature?
@danielwilhelm

**Comment by danielwilhelm** [comment]
Sigma sounds good. Let's use that.
