### ISSUE TITLE
update references

### ISSUE THREAD

**Issue by danielwilhelm** [danielwilhelm/R-CS-ranks#15]
all references to the paper should be updated, the correct citation is: 

Mogstad, Romano, Shaikh, and Wilhelm (2023), "Inference for Ranks with Applications to Mobility across Neighborhoods and Academic Achievements across Countries", forthcoming at Review of Economic Studies

and the updated paper is here: http://dwilhelm.userweb.mwn.de/papers/cwp0323.pdf

**Comment by MrDomani** [comment]
Does this apply also to function `csranks_multinom`? It has a different paper in references

**Comment by danielwilhelm** [comment]
Thanks for checking. No, the cranks_multinom is based on a different paper. That reference can stay the same.
