### ISSUE TITLE
multcorr = none

### ISSUE THREAD

**Issue by MrDomani** [danielwilhelm/R-CS-ranks#18]
In documentation of `csranks_multinom` it is mentioned, that one of possible values for `multcorr` is `none`. However, the code itself (of function and tests) does not handle this case.

Should we allow user to pass `none`, or should not and delete this fragment of documentation? In my opinion, the second option is better.
@danielwilhelm

**Comment by danielwilhelm** [comment]
I agree, let's remove the option "none" from the documentation
