### ISSUE TITLE
allow estimates to be correlated

### ISSUE THREAD

**Issue by danielwilhelm** [danielwilhelm/R-CS-ranks#3]
- currently, csranks() takes arguments the vectors x and sd, the estimates and their standard deviations, assuming that the elements of x are not correlated
- the bootstrap draws generated in csranks() are from a normal with mean zero and covariance matrix that has diagonal equal to sd and all other elements equal to 0
- we want to allow for correlation
- this can be done by passing as an argument the covariance matrix of x instead of sd
- then, the bootstrap draws generated in csranks() must be from a normal distribution with mean zero and that covariance matrix (instead of a diagonal the diagonal matrix with sd on the diagonal)

**Comment by MrDomani** [comment]
Ready on branch `dev`. Pull will be requested soon.
