### ISSUE TITLE
Optimize fitting projection models

### ISSUE THREAD

**Issue by MrDomani** [danielwilhelm/R-CS-ranks#33]
In vcov we are fitting a lot of linear models based on very similar data, calling lm p times (p-number of columns). Maybe we could do it more optimally. Need to think, read, and think more.

**Comment by MrDomani** [comment]
I found a way to calculate coefficients of projection models directly from the original `lmranks` object, in a much more efficient way that fitting p linear models. I am working also on optimizing code s.t. it uses more matrix multiplications and less loops (sapply's) with inner products within.

**Comment by danielwilhelm** [comment]
Great! And you are testing the modifications to make sure that the results stay the same?

**Comment by MrDomani** [comment]
Of course. Right now all the changes are on a local branch on my computer; when ready & tested, I will push them to `dev` branch and make a pull request to master.
