### ISSUE TITLE
implementation of lmranks with decreasing rankings

### ISSUE THREAD

**Issue by danielwilhelm** [danielwilhelm/R-CS-ranks#37]
Implement lmranks with increasing=FALSE:

the formulas for the asymptotic variance stay the same as for increasing=TRUE, except that in the indicators I(...), inequalities are reversed, so <= becomes >= and < becomes > everywhere.

**Comment by MrDomani** [comment]
So I guess, that all we have to do is negate the regressor to be ranked, i.e.
`lmranks(r(y, increasing=FALSE)~...)` is the same as `lmranks(r(-y, increasing=TRUE)~...)`.
I will prepare an end2end test with indicators reversed, implement increasing=FALSE by negation and check whether results are the same.

**Comment by danielwilhelm** [comment]
This issue has been addressed on the vignette branch, correct? If so, we can close this one ...

**Comment by MrDomani** [comment]
Exactly.
