### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by danielwilhelm** [danielwilhelm/R-CS-ranks#4]
go through https://danielwilhelm.github.io/R-CS-ranks/index.html and the description of functions on https://danielwilhelm.github.io/R-CS-ranks/reference/index.html and improve the documentation

**Comment by MrDomani** [comment]
Work in progress on branch `doc`.  
A lot of functions share the same parameters, output and references. Roxygen (tool for generating documentation, which we are using) enables us to share documentation sections across functions (e.g. with inheritParams tag, more [here]()). Which means, that when we edit one, documentations for all shared functions are updated automatically.

Some unexported functions are also documented in code. This is considered a [good practice](https://style.tidyverse.org/documentation.html#internal-functions). Right now, users can see their documentation pages, but cannot use the functions themselves. This can be easily resolved by noRd tag. Then their documentation is only visible in source code. 

However, these functions also share parameters with other functions. 
What I propose to do is add noRd tags to internal (not exported) functions and use inherit tags extensively. When viewing an internal function with inherit tag, the developer can check them in docs of other functions - either manually or with `?`, when possible.

**Comment by danielwilhelm** [comment]
Perfect! Also all good ideas!

**Comment by MrDomani** [comment]
- [ ] Create an example with dependent estimates (and adapt one with independent)
- [ ] Emphasize, that we expect covariance matrix of ESTIMATORS, not populations
- [ ]  Include an example of customization of plot from `plotranking`
