### ISSUE TITLE
Update settings

### ISSUE THREAD

**Issue by MrDomani** [danielwilhelm/R-CS-ranks#9]
Pkgdown site still shows old version. I believe, that the reason is, that it's still reading data from docs folder in master branch, instead of from gh-pages branch . I am certain, that that can be changed from repository settings, but I do not have access to them.

**Comment by danielwilhelm** [comment]
Ok, I have changed the setting, so the page is now deployed from the branch gh-pages - see screenshot. Is this what you meant?
<img width="835" alt="Screenshot 2022-12-24 at 11 13 47" src="https://user-images.githubusercontent.com/928660/209431508-67642fab-56cd-43ce-a680-69a74d7ebef9.png">

**Comment by MrDomani** [comment]
Almost. Branch is correct, please change the folder from `/docs` to `/` (root of the repository).

**Comment by danielwilhelm** [comment]
ok, done

**Comment by MrDomani** [comment]
Wondeful. The package site is up to date.
